//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectezeze.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionStage : DbContext
    {
        public GestionStage()
            : base("name=GestionStage")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Absence> Absence { get; set; }
        public virtual DbSet<Alerte> Alerte { get; set; }
        public virtual DbSet<Historique> Historique { get; set; }
        public virtual DbSet<PieceJointe> PieceJointe { get; set; }
        public virtual DbSet<Stage> Stage { get; set; }
        public virtual DbSet<Stagiaire> Stagiaire { get; set; }
        public virtual DbSet<Tache> Tache { get; set; }
        public virtual DbSet<Tach> Tache1 { get; set; }
        public virtual DbSet<TypeRole> TypeRole { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
    }
}
