//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectezeze.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeRole
    {
        public int IdRole { get; set; }
        public Nullable<int> IdUtilisateur { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Role { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
